### PR TITLE
assets/dashboard_nav: give button absolute position to ensure whole a…

### LINKED ISSUE #1425: adding modules to project and publish project: button not active after adding modules
**URL:** https://aplus-dev.liqd.net/frede-test/dashboard/modules/brainstorming-50/phases/
**user:** initiator
**expected behaviour:** i would expect to be able to publish projects after adding a module and filling out everything
**behaviour:** the "publish" button is not active after adding a module. When i reload the page the module is not added anymore.
**important screensize:** all sizes
**device & browser:** macOS 11.4, Safari 14.1.1, Chrome Version 92.0.4515.159
**Comment/Question:** 

Screenshot?
Bildschirmfoto 2021-09-07 um 15 15 40

### PR DESCRIPTION
**Pull request by phillimorland**
…rea bot toggles and updates publish value fixes #1425

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
I can reproduce the issue in my chromium and this doesn't seem to fix it. :( But I will try again tomorrow, sometimes updating the css-stuff doesn't work.

**Comment by phillimorland** [comment]
no you're right it's broken in chrome, damm! will recheck

**Comment by phillimorland** [comment]
> I can reproduce the issue in my chromium (version 93.0.4577.63) and this doesn't seem to fix it. :( But I will try again tomorrow, sometimes updating the css-stuff doesn't work.

should now work

**Review by fuzzylogic2000 — APPROVED** [review]
Yeah! This fixes it!

**Pull request merged**
