### PR TITLE
Kl 2021 09 migrate polls

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
Analogous to https://github.com/liqd/a4-meinberlin/pull/3647, but going further as we can use all poll code from a4 directly.

Styling is still missing!

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Right, this also breaks the comments styling, because we use the template from a4. Instead of overwriting that in here using the new comments, we should overwrite in mB with the old ones?! And change the template in a4. Are we also overwriting the poll detail in opin?

**Comment by fuzzylogic2000** [comment]
@phillimorland @Rineee @sabinammm @khamui Could you all test it? And then if the DBs are fine and the same question, votes and comments are shown as before, we can merge and style afterwards?

**Comment by phillimorland** [comment]
@fuzzylogic2000 mine is working fine but I had an almost empty database, so wam hesitent to merge, i'll work on here for styling and if someone with an older database can also test that would be better

**Comment by sabinammm** [comment]
I tested it also with a database with a few things and some comments. It works fine for me. I still don't really understand this, but I did notice that the "content_type": had a different value after migration.

**Comment by fuzzylogic2000** [comment]
So, let's wait for at least @Rineee to also test. :)

**Review by Rineee — COMMENTED** [review]
Yes, its looking good and works well!

**Pull request merged**
