### PR TITLE
ideas/serializers: add creator and created to serializer

### PR DESCRIPTION
**Pull request by Rineee**
@khamui  Can you work with the format of the date?

### CODE REVIEW

**Review by fuzzylogic2000 — APPROVED** [review]
Very nice! Should we just merge and fix the date later if need be?

**Comment by Kha** [comment]
> @Kha Can you work with the format of the date?

I can't, because I'm not @khamui

**Comment by Rineee** [comment]
> > @Kha Can you work with the format of the date?
> 
> I can't, because I'm not @khamui

:see_no_evil: :sweat_smile: Ups, sorry and thanks for the hint!

**Comment by khamui** [comment]
@Rineee so i tested this endpoint. The date is fine and works!

Two things i figured out, one is that if its possible to include the `Ref. No.` information?
And the `description` and maybe `title` field are containing html tags. Is it possible to just send the string without html tags?

For example: `"<p>wowowowowow</p>"` without the `<p>`

**Comment by fuzzylogic2000** [comment]
> Two things i figured out, one is that if its possible to include the `Ref. No.` information?
> And the `description` and maybe `title` field are containing html tags. Is it possible to just send the string without html tags?
> 
> For example: `"<p>wowowowowow</p>"` without the `<p>`

Oh no, right, we have richtext. The question is: are we allowed to get rid of the markup or do we also need to display it in the app (the <p> doesn't matter, but we also have bold and italic and maybe more?).

**Comment by khamui** [comment]
Syntactically I think JSX in react-native does not understand any html notations. There are third party libs which make it possible, but I would suggest to not create that dependency, because....

To meet and being flexible in terms of designs i think we should only pass plain text. So the responsibility of its appearance is wherever it is used. In this case the app.

**Comment by Rineee** [comment]
@khamui I added the reference_number and as discussed left rich text until we have a solution/decision for that

**Review by fuzzylogic2000 — APPROVED** [review]
Looks good! Can we merge @khamui ? Then, we can use it in the idea views!

**Pull request merged**
