### PR TITLE
makefile: bugfix for syntax error (unterminated quoted string)

### PR DESCRIPTION
**Pull request by hklarner**

### CODE REVIEW

**Review by m4ra — CHANGES_REQUESTED** [review]
yes we caught this on the celery PR in meinberlin. there are a couple more small improvements that you can include here, see the review comments [here](https://github.com/liqd/a4-meinberlin/pull/5240)

**Comment by hklarner** [comment]
> yes we caught this on the celery PR in meinberlin. thttps://github.com/liqd/a4-meinberlin/pull/5240 are a couple more small improvements that you can include here, see the review comments here

I see. @m4ra I looked at the PR you linked to. Which changes are you referring to? I cannot find additional changes.

**Comment by m4ra** [comment]
> I see. @m4ra I looked at the PR you linked to. Which changes are you referring to? I cannot find additional changes.
check the outdated/resolved discussions
image

**Comment by hklarner** [comment]
- makefile: nothing to do
- readme: changed the redis bullet point
- docs/celery: added `"and install and run the redis server on your system."`
- requirements/base.txt: moved redis import from "a4" to "additional"

@m4ra can you check this is what you want?

**Review by m4ra — APPROVED** [review]
thank you

**Pull request merged**
