### PR TITLE
Change the wording of the help text for the map component

### PR DESCRIPTION
**Pull request by P4rcev4l**
not sure how things work with translation

### CODE REVIEW

**Comment by P4rcev4l** [comment]
I'm not sure if I changed the correct files, in fact I'm pretty sure I didn't given that the CI fail. I need some pointers here

**Comment by goapunk** [comment]
@P4rcev4l I think the correct place to change it is here: https://github.com/liqd/adhocracy-plus/blob/main/apps/mapideas/models.py#L16

**Comment by goapunk** [comment]
added the missing migrations

**Review by goapunk — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
