### PR TITLE
style.scss: update config to only load required components, add fix t…

### LINKED ISSUE #1622: debate list: list tile is clicked when dropdown ordeing filter clicked
**URL:** https://aplus-dev.liqd.net/liqd-tests/projects/test-the-debate/
**user:** 
**expected behaviour:** 
**behaviour:** When I try to order by "most comments", instead of choosing the filter in the dropdown, the debate subject tile is clicked and I am taken to the detail page.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
…o variables

check out https://github.com/liqd/adhocracy-plus/pull/1466

fixes #1622

### CODE REVIEW

**Review by fuzzylogic2000 — COMMENTED** [review]
@phillimorland Is this still a thing that we want to do? Then maybe now with the updates and the extensive testing is a good idea? (You originally opened the PR, but now it is in my name because of the master/main rename)

**Comment by phillimorland** [comment]
@fuzzylogic2000 I was wondering where that was :p yes I would still like to try it as it's possible bootstrap causes the map upload thing, will try to get it up to date this morning!

**Review by fuzzylogic2000 — COMMENTED** [review]
Looks good, also in the browser. 
I cannot reproduce the failing test locally. :(

**Comment by fuzzylogic2000** [comment]
> Looks good, also in the browser. I cannot reproduce the failing test locally. :(

But the test is not failing anymore after running them again. :)

**Pull request merged**
