### PR TITLE
comments_async/date: break date into new line

### PR DESCRIPTION
**Pull request by khamui**

### CODE REVIEW

**Comment by Rineee** [comment]
@khamui Oh, did we forget about this? This fixes #1787, right?

**Comment by khamui** [comment]
@Rineee oh, yes oops..

**Comment by phillimorland** [comment]
doesn't this need a4 update before it's ready for review?

**Comment by khamui** [comment]
oh okay, should have removed it back then. so generally we remove this label, when a4 (that this is depending on) was merged right?

**Comment by phillimorland** [comment]
@khamui for a4 depending pull requests it's a bit messy as you can't really test one without the other so you should always have a4 label and always include the link to the a4 PR in the depending PR so they can be tested together, if it's fine then the tester can then merge the a4 one and either inform the creator that their app PR can be merged after they update the a4 hash or the tested can do it themselves if they have time, it's not really a perfect system, sorry!

**Pull request merged**
