### PR TITLE
Ks 2021 05 more tests

### PR DESCRIPTION
**Pull request by Rineee**
@fuzzylogic2000 I was tempted to remove [this](https://github.com/liqd/adhocracy-plus/blob/3d521b9307dd415c76cbc6fcd0ee8fdb7a7e3de3/apps/dashboard/views.py#L192-L197) from ModuleDeleteView, because I think we dont need it anymore, right? Because the dropdown with deletion option only shows if module is draft? But then I saw that these lines were only added a year ago, so not sure anymore.. do we still need that?

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 I was tempted to remove [this](https://github.com/liqd/adhocracy-plus/blob/3d521b9307dd415c76cbc6fcd0ee8fdb7a7e3de3/apps/dashboard/views.py#L192-L197) from ModuleDeleteView, because I think we dont need it anymore, right? Because the dropdown with deletion option only shows if module is draft? But then I saw that these lines were only added a year ago, so not sure anymore.. do we still need that?

I think we do, because it is two different things to me: we only show the button when the module is a draft anymore. But someone could still post to the view when a module is already published. Or add a button somewhere that does that. So, the view should still handle that!

**Review by fuzzylogic2000 — APPROVED** [review]
Sooooo cool! You made it to > 85%! Nearly +1%! :tada:

**Comment by fuzzylogic2000** [comment]
Is it still WIP? Or can we merge?

**Comment by Rineee** [comment]
> > @fuzzylogic2000 I was tempted to remove [this](https://github.com/liqd/adhocracy-plus/blob/3d521b9307dd415c76cbc6fcd0ee8fdb7a7e3de3/apps/dashboard/views.py#L192-L197) from ModuleDeleteView, because I think we dont need it anymore, right? Because the dropdown with deletion option only shows if module is draft? But then I saw that these lines were only added a year ago, so not sure anymore.. do we still need that?
> 
> I think we do, because it is two different things to me: we only show the button when the module is a draft anymore. But someone could still post to the view when a module is already published. Or add a button somewhere that does that. So, the view should still handle that!

Alright, then I will also test it. In meinBerlin, we dont have that btw, I'll add an issue.

**Comment by Rineee** [comment]
> Is it still WIP? Or can we merge?

Sorry, just quickly added testing if module is draft when deleting. Now its ready!

**Pull request merged**
