### PR TITLE
Kl 2021 02 captcha

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
This should be enough to start working on the DB - we can add the more complicated wagtail form captcha stuff later.

### CODE REVIEW

**Review by rmader — APPROVED** [review]
LGTM. Nit: I personally prefer if commits within a MR do not first add and then remove something again, even though it's understandable in the case here :)

**Comment by fuzzylogic2000** [comment]
@rmader  If you prefer, that I squash it, I can also do that.

**Comment by fuzzylogic2000** [comment]
@rmader It did work! Do you want to merge or should I?

**Review by rmader — APPROVED** [review]
LGTM!

**Pull request merged**
