### PR TITLE
desp: planifolia remove unused css classes

### PR DESCRIPTION
**Pull request by khamui**
the branch with a lot of file changes i can't push, because it does not pass husky :(
but i have it locally, in case we want to have a look i can create a patch i guess.

current state: need replacement mixins/functions for commented out:
`grid-*`
`contrast()`
`mix()`
`luma()`

### CODE REVIEW

**Comment by phillimorland** [comment]
@khamui just to show you what I meant when we talked, instead of deleting references to code we need like you did in the other pr, when updating or removing packages like this, I find it best to just comment out everything that is causing failed install. Once its installed then go through it function by function or whatever and fix what has been commented out for like for like code/functions. We can talk about this again as we need to deal with it during next sprint.

**Comment by khamui** [comment]
oh, this PR was rather a working (with planifolia) but removed the definitely unused classes. Because i didn't know how soon we will make the bigger shift.

but yeah, its not a lot that is unused.

**Comment by fuzzylogic2000** [comment]
@phillimorland @khamui What is the status? Should we merge before release or rather not?

**Comment by phillimorland** [comment]
@fuzzylogic2000 no this will be touched again when we do the button update story https://taiga.liqd.net/project/liqd-liquid-product/us/254?no-milestone=1

**Pull request closed without merging**
