### PR TITLE
[7637] django upgrade to 4.2

### PR DESCRIPTION
**Pull request by m4ra**
To be merged after wagtail upgrade [#2554](https://github.com/liqd/adhocracy-plus/pull/2554/)

**Tasks**
- [x] PR name contains story or task reference
- [ ] Documentation (docs and inline)
- [ ] Tests (including n+1 and django_assert_num_queries where applicable)
- [x] Changelog

### CODE REVIEW

**Comment by m4ra** [comment]
@goapunk there is an issue with the background task app. So I will rebase this PR once you merge https://github.com/liqd/adhocracy-plus/pull/2542 into main.

**Review by goapunk — CHANGES_REQUESTED** [review]
Nice, looks good, just one thing which I think is missing: the delete() -> form_valid() change was part of this update already

**Review by goapunk — APPROVED** [review]
Really nice! Only thing we need to take into account is that by updating the a4 hash we now have the ckeditor5 changes, so we can't release this until we did the ckeditor5 story

**Comment by m4ra** [comment]
@goapunk or we don't update the a4 hash.

**Comment by goapunk** [comment]
> @goapunk or we don't update the a4 hash.

will it cause problems with a4 on django 3.2 and a+ on django 4.2 if we don't update the hash?

**Comment by m4ra** [comment]
@goapunk the topics might be an issue, though we don't use it in a+. Need to check if ckeditor was added after the multiselect-field.

**Review by goapunk — APPROVED** [review]
LGTM, we didn't do the deprecated app config bit but we can do them in a new PR and get this merged I'd say

**Pull request merged**
