### PR TITLE
WIP: cms/blocks.py: remove choice option to choose cols and update templat…

### PR DESCRIPTION
**Pull request by phillimorland**
…e incl migration
@fuzzylogic2000 when I got into this, i found that a lot of what I did was very messy and would like to refactor a lot but for right now, I just updated that block. I'm not sure however if this is the best way to go about doing it? it is kind of done this way in ae/ce but I would like your opinion

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Hmm, it's reusabilty vs. making blocks exactly for what they are meant to do, right? I would go a bit more in the direction of the latter. Maybe reusabilty makes sense for some columns, but if the styles are very restrictive and the blocks have to be set up a certain way for that to work, I think it's easiest if we just allow the certain way for the whole block.

**Comment by phillimorland** [comment]
@fuzzylogic2000 i messed up migrations by renaming, i'll redo and tag you

**Comment by phillimorland** [comment]
@fuzzylogic2000 what do we need to do on this now?

**Comment by fuzzylogic2000** [comment]
@phillimorland I still need to get the migrations right, but don't know how to go on about it. I think, I need to test what we need and how to get the old stuff into the new models.

**Comment by phillimorland** [comment]
ok if you want to pair on it hit me up!

**Comment by fuzzylogic2000** [comment]
will hopefully replaced by #1295

**Pull request closed without merging**
